/*---------------------------------------------------------------------------
 * Copyright (c) 2025 Arm Limited (or its affiliates).
 * All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *---------------------------------------------------------------------------*/

// Vendor:    Infineon
// Device:    CYT4BF8CDS
// Processor: Cortex-M7
// Project:   TrafficLight

#include "zones.h"

#ifdef   _RTE_
#include "RTE_Components.h"
#endif
#include CMSIS_device_header

#include "mem_layout.h"                 // Memory layout header

#include "faults.h"
#include "cmsis_os2.h"

#define MPU_REGIONS                     8U

static const ARM_MPU_Region_t mpu_table[ZONES_NUM][MPU_REGIONS];

/* Initialize Zones (MPU) settings */
void ZonesInitialize (void) {

  /* Enable privileged default access */
  ARM_MPU_Enable(MPU_CTRL_PRIVDEFENA_Msk);
}

/* Update MPU settings for newly activating Zone */
void osZoneSetup_Callback (uint32_t zone) {

  if (zone >= ZONES_NUM) {
    ZoneError_Handler();
  }

  ARM_MPU_Disable();
  ARM_MPU_Load(mpu_table[zone], MPU_REGIONS);
  ARM_MPU_Enable(MPU_CTRL_PRIVDEFENA_Msk);
}

/* MPU table specifying MPU regions for all Zones */
static const ARM_MPU_Region_t mpu_table[ZONES_NUM][MPU_REGIONS] = {
  /* Zone 'Zone_Normal_OP' */ 
  {
    // FLASH (0x10080000..0x1017FFFF)
    { .RBAR = ARM_MPU_RBAR(0U, 0x10080000), .RASR = ARM_MPU_RASR_EX(0U, ARM_MPU_AP_RO,   ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0xE1U, ARM_MPU_REGION_SIZE_4MB) },
    // RAM_SHARED + RAM_EVR (0x28020000..0x28023FFF)
    { .RBAR = ARM_MPU_RBAR(1U, 0x28020000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_16KB) },
    // RAM_NORMAL_OP (0x28024000..0x28024FFF)
    { .RBAR = ARM_MPU_RBAR(2U, 0x28024000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_4KB) },
    // GPIO PORT5 (0x40310280..0x403102FF) for LEDs and button
    { .RBAR = ARM_MPU_RBAR(3U, 0x40310280), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_DEVICE(1U),                                                 0x00U, ARM_MPU_REGION_SIZE_128B) },
    { .RBAR = ARM_MPU_RBAR(4U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(5U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(6U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(7U, 0U), .RASR = 0U }
  },
  /* Zone 'Zone_Verify_OP' */ 
  {
    // FLASH (0x10080000..0x1017FFFF)
    { .RBAR = ARM_MPU_RBAR(0U, 0x10080000), .RASR = ARM_MPU_RASR_EX(0U, ARM_MPU_AP_RO,   ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0xE1U, ARM_MPU_REGION_SIZE_4MB) },
    // RAM_SHARED + RAM_EVR (0x28020000..0x28023FFF)
    { .RBAR = ARM_MPU_RBAR(1U, 0x28020000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_16KB) },
    // RAM_VERIFY_OP (0x28025000..0x28025FFF)
    { .RBAR = ARM_MPU_RBAR(2U, 0x28025000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_4KB) },
    { .RBAR = ARM_MPU_RBAR(3U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(4U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(5U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(6U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(7U, 0U), .RASR = 0U }
  },
  /* Zone 'Zone_Com' */ 
  {
    // FLASH (0x10080000..0x1017FFFF)
    { .RBAR = ARM_MPU_RBAR(0U, 0x10080000), .RASR = ARM_MPU_RASR_EX(0U, ARM_MPU_AP_RO,   ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0xE1U, ARM_MPU_REGION_SIZE_4MB) },
    // RAM_SHARED + RAM_EVR (0x28020000..0x28023FFF)
    { .RBAR = ARM_MPU_RBAR(1U, 0x28020000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_16KB) },
    // RAM_COM (0x28010000..0x2801FFFF)
    { .RBAR = ARM_MPU_RBAR(2U, 0x28010000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_64KB) },
    // Whole RAM (0x28000000..0x283FFFFF)
    { .RBAR = ARM_MPU_RBAR(3U, 0x28000000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_8MB) },
//  // RAM for interrupt handler addresses (0x28004000..0x28004FFF)
//  { .RBAR = ARM_MPU_RBAR(3U, 0x28004000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_4KB) },
    // Peripherals (0x40000000..0x43FFFFFF)
    { .RBAR = ARM_MPU_RBAR(4U, 0x40000000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_DEVICE(1U),                                                 0x00U, ARM_MPU_REGION_SIZE_64MB) },
//  // ETH0 (0x40480000..0x4048FFFF)
//  { .RBAR = ARM_MPU_RBAR(4U, 0x40480000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_DEVICE(1U),                                                 0x00U, ARM_MPU_REGION_SIZE_64KB) },
    { .RBAR = ARM_MPU_RBAR(5U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(6U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(7U, 0U), .RASR = 0U }
  },
  /* Zone 'Zone_Safe_OP' */ 
  {
    // FLASH (0x10080000..0x1017FFFF)
    { .RBAR = ARM_MPU_RBAR(0U, 0x10080000), .RASR = ARM_MPU_RASR_EX(0U, ARM_MPU_AP_RO,   ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0xE1U, ARM_MPU_REGION_SIZE_4MB) },
    // RAM_SHARED + RAM_EVR (0x28020000..0x28023FFF)
    { .RBAR = ARM_MPU_RBAR(1U, 0x28020000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_16KB) },
    // RAM_SAFE_OP (0x28026000..0x28026FFF)
    { .RBAR = ARM_MPU_RBAR(2U, 0x28026000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_4KB) },
    // GPIO PORT5 (0x40310280..0x403102FF) for LEDs and button
    { .RBAR = ARM_MPU_RBAR(3U, 0x40310280), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_DEVICE(1U),                                                 0x00U, ARM_MPU_REGION_SIZE_128B) },
    // WDT (0x4026C000..0x4026C07F)
    { .RBAR = ARM_MPU_RBAR(4U, 0x4026C000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_DEVICE(1U),                                                 0x00U, ARM_MPU_REGION_SIZE_128B) },
    { .RBAR = ARM_MPU_RBAR(5U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(6U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(7U, 0U), .RASR = 0U }
  },
  /* Zone 'Zone_Timer' */ 
  {
    // FLASH (0x10080000..0x1017FFFF)
    { .RBAR = ARM_MPU_RBAR(0U, 0x10080000), .RASR = ARM_MPU_RASR_EX(0U, ARM_MPU_AP_RO,   ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0xE1U, ARM_MPU_REGION_SIZE_4MB) },
    // RAM_SHARED + RAM_EVR (0x28020000..0x28023FFF)
    { .RBAR = ARM_MPU_RBAR(1U, 0x28020000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_16KB) },
    // RAM_COM (0x28010000..0x2801FFFF)
    { .RBAR = ARM_MPU_RBAR(2U, 0x28010000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_64KB) },
    // RAM_TIMER (0x28027000..0x28027FFF)
    { .RBAR = ARM_MPU_RBAR(3U, 0x28027000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_4KB) },
    { .RBAR = ARM_MPU_RBAR(4U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(5U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(6U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(7U, 0U), .RASR = 0U }
  },
  /* Zone 'Zone_Idle' */ 
  {
    // FLASH (0x10080000..0x1017FFFF)
    { .RBAR = ARM_MPU_RBAR(0U, 0x10080000), .RASR = ARM_MPU_RASR_EX(0U, ARM_MPU_AP_RO,   ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0xE1U, ARM_MPU_REGION_SIZE_4MB) },
    // RAM_SHARED + RAM_EVR (0x28020000..0x28023FFF)
    { .RBAR = ARM_MPU_RBAR(1U, 0x28020000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_16KB) },
    // RAM_IDLE (0x28028000..0x28028FFF)
    { .RBAR = ARM_MPU_RBAR(2U, 0x28028000), .RASR = ARM_MPU_RASR_EX(1U, ARM_MPU_AP_FULL, ARM_MPU_ACCESS_NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, 0U), 0x00U, ARM_MPU_REGION_SIZE_4KB) },
    { .RBAR = ARM_MPU_RBAR(3U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(4U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(5U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(6U, 0U), .RASR = 0U },
    { .RBAR = ARM_MPU_RBAR(7U, 0U), .RASR = 0U }
  }
};

#warning Correct RAM area and add peripherals for Communication Zone once Ethernet driver is stable
